// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TwitterClone.Infrastructure.Persistence;

#nullable disable

namespace TwitterClone.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260616153124_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.9")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("TwitterClone.Domain.Entities.Follow", b =>
            {
                b.Property<Guid>("FollowerId")
                    .HasColumnType("uuid");

                b.Property<Guid>("FolloweeId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("FollowerId", "FolloweeId");

                b.HasIndex("FolloweeId");

                b.ToTable("follows", (string)null);
            });

        modelBuilder.Entity("TwitterClone.Domain.Entities.Like", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.Property<Guid>("TweetId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("UserId", "TweetId");

                b.HasIndex("TweetId");

                b.ToTable("likes", (string)null);
            });

        modelBuilder.Entity("TwitterClone.Domain.Entities.RefreshToken", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsRevoked")
                    .HasColumnType("boolean");

                b.Property<string>("TokenHash")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("TokenHash")
                    .IsUnique();

                b.HasIndex("UserId");

                b.ToTable("refresh_tokens", (string)null);
            });

        modelBuilder.Entity("TwitterClone.Domain.Entities.Tweet", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("AuthorId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("ImageUrl")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)");

                b.Property<Guid?>("ParentId")
                    .HasColumnType("uuid");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasMaxLength(280)
                    .HasColumnType("character varying(280)");

                b.HasKey("Id");

                b.HasIndex("AuthorId");

                b.HasIndex("CreatedAt");

                b.HasIndex("ParentId");

                b.ToTable("tweets", (string)null);
            });

        modelBuilder.Entity("TwitterClone.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("AvatarUrl")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)");

                b.Property<string>("Bio")
                    .HasMaxLength(160)
                    .HasColumnType("character varying(160)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.HasIndex("Username")
                    .IsUnique();

                b.ToTable("users", (string)null);
            });

        modelBuilder.Entity("TwitterClone.Domain.Entities.Follow", b =>
            {
                b.HasOne("TwitterClone.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("FolloweeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("TwitterClone.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("FollowerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("TwitterClone.Domain.Entities.Like", b =>
            {
                b.HasOne("TwitterClone.Domain.Entities.Tweet", null)
                    .WithMany()
                    .HasForeignKey("TweetId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("TwitterClone.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("TwitterClone.Domain.Entities.RefreshToken", b =>
            {
                b.HasOne("TwitterClone.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("TwitterClone.Domain.Entities.Tweet", b =>
            {
                b.HasOne("TwitterClone.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("AuthorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("TwitterClone.Domain.Entities.Tweet", null)
                    .WithMany()
                    .HasForeignKey("ParentId")
                    .OnDelete(DeleteBehavior.Restrict);
            });
#pragma warning restore 612, 618
    }
}
